spring:
  profiles:
    active: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    open-in-view: false
server:
  port: 9528
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:mysql:///vgtime_imitation?serverTimezone=GMT%2B8
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://mysql/vgtime_imitation?serverTimezone=GMT%2B8
vgtime-imitation:
  comment:
    enabled: false # 根据相关法律法规，个人备案的网站不允许开启评论功能
