spring:
  profiles:
    active: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
server:
  port: 9528
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:mysql:///vgtime_imitation?serverTimezone=GMT%2B8
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://mysql/vgtime_imitation?serverTimezone=GMT%2B8
